#!/usr/bin/env node
// One-shot extractor: lifts the verified data tables out of the legacy
// index.html into real ES modules under src/data/.
//
// Done mechanically rather than by hand on purpose. These tables are the most
// valuable thing in the old codebase — 39 audited ACS variable codes, 28
// fortified templates, 50 draft categories, 16 themes, the FIPS map — and
// re-typing them is exactly how a rewrite silently loses data.
//
// Usage: node scripts/extract-data.mjs [--check]
//   --check  re-extract and diff against what's on disk (CI-friendly)

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SRC = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');
const OUT_DIR = path.join(ROOT, 'src', 'data');

/**
 * Find `const <name> = ` and return the complete initializer source by
 * matching brackets, ignoring anything inside strings, template literals,
 * comments, or regex-looking slashes.
 */
function readDeclaration(name) {
  const decl = new RegExp(`\\bconst\\s+${name}\\s*=\\s*`, 'g');
  const m = decl.exec(SRC);
  if (!m) throw new Error(`declaration not found: ${name}`);
  let i = m.index + m[0].length;

  const OPEN = { '{': '}', '[': ']', '(': ')' };
  const first = SRC[i];
  if (!OPEN[first]) throw new Error(`${name} does not start with a bracket (got ${JSON.stringify(first)})`);

  const stack = [];
  let inStr = null, inTemplate = false, inLineComment = false, inBlockComment = false, esc = false;

  for (; i < SRC.length; i++) {
    const c = SRC[i], next = SRC[i + 1];

    if (esc) { esc = false; continue; }
    if (inStr) {
      if (c === '\\') { esc = true; continue; }
      if (c === inStr) inStr = null;
      continue;
    }
    if (inTemplate) {
      if (c === '\\') { esc = true; continue; }
      if (c === '`') inTemplate = false;
      continue;
    }
    if (inLineComment) { if (c === '\n') inLineComment = false; continue; }
    if (inBlockComment) { if (c === '*' && next === '/') { inBlockComment = false; i++; } continue; }

    if (c === '/' && next === '/') { inLineComment = true; i++; continue; }
    if (c === '/' && next === '*') { inBlockComment = true; i++; continue; }
    if (c === '"' || c === "'") { inStr = c; continue; }
    if (c === '`') { inTemplate = true; continue; }

    if (OPEN[c]) { stack.push(OPEN[c]); continue; }
    if (c === '}' || c === ']' || c === ')') {
      const want = stack.pop();
      if (want !== c) throw new Error(`${name}: bracket mismatch at offset ${i} (wanted ${want}, got ${c})`);
      if (!stack.length) return SRC.slice(m.index + m[0].length, i + 1);
    }
  }
  throw new Error(`${name}: unterminated initializer`);
}

const HEADER = (names) => `// GENERATED by scripts/extract-data.mjs from the legacy index.html.
// Source of truth for: ${names}.
// Re-run \`node scripts/extract-data.mjs\` to refresh; \`--check\` verifies it
// still matches. Edit the values here once the legacy file is retired.
`;

const MODULES = [
  {
    file: 'states.js',
    decls: [['FIPS_TO_STATE', 'fipsToState']],
    extra: `
// Excluded from the "X of 50 states colored" count.
export const NON_COLORABLE = new Set(['District of Columbia']);

/** All 50 state names, sorted. Excludes DC and territories. */
export const STATE_NAMES = Object.values(FIPS_TO_STATE)
  .filter((n) => !NON_COLORABLE.has(n))
  .sort();

/** name -> FIPS, derived so the two can never drift apart. */
export const STATE_TO_FIPS = Object.fromEntries(
  Object.entries(FIPS_TO_STATE).map(([fips, name]) => [name, fips])
);
`,
  },
  { file: 'datasets.js', decls: [['DATA_MAP_DATASETS', 'DATA_MAP_DATASETS']] },
  { file: 'templates.js', decls: [['TEMPLATES', 'TEMPLATES']] },
  { file: 'themes.js', decls: [['THEME_LIST', 'themeList']] },
  {
    file: 'ramps.js',
    decls: [
      ['COLOR_RAMPS', 'colorRamps'],
      ['RAMP_NAMES', 'rampNames'],
      ['DEFAULT_PRESET_COLORS', 'defaultPresetColors'],
      ['EXTRA_PALETTES', 'extraPalettes'],
      ['COLORBLIND_PALETTES', 'colorblindPalettes'],
      ['DATA_MAP_RAMPS', 'DATA_MAP_RAMPS'],
    ],
  },
  {
    file: 'draft-categories.js',
    decls: [
      ['DRAFT_AREA', 'DRAFT_AREA'],
      ['DRAFT_STATEHOOD', 'DRAFT_STATEHOOD'],
      ['DRAFT_HIGHPOINT', 'DRAFT_HIGHPOINT'],
      ['DRAFT_MEAN_ELEV', 'DRAFT_MEAN_ELEV'],
      ['DRAFT_COUNTIES', 'DRAFT_COUNTIES'],
      ['DRAFT_COASTLINE', 'DRAFT_COASTLINE'],
      ['DRAFT_EV', 'DRAFT_EV'],
      ['DRAFT_PRESIDENTS', 'DRAFT_PRESIDENTS'],
      ['DRAFT_PARKS', 'DRAFT_PARKS'],
      ['DRAFT_BORDERS', 'DRAFT_BORDERS'],
    ],
  },
  { file: 'arcade-games.js', decls: [['ARCADE_GAMES', 'ARCADE_GAMES'], ['ARCADE_HOWTO', 'ARCADE_HOWTO']] },
  { file: 'quick-fill.js', decls: [['QUICK_FILL_GROUPS', 'quickFillGroups']] },
];

const check = process.argv.includes('--check');
fs.mkdirSync(OUT_DIR, { recursive: true });

let changed = 0;
for (const mod of MODULES) {
  const parts = [HEADER(mod.decls.map(([exportName]) => exportName).join(', '))];
  for (const [exportName, sourceName] of mod.decls) {
    const body = readDeclaration(sourceName);
    parts.push(`\nexport const ${exportName} = ${body};\n`);
  }
  if (mod.extra) parts.push(mod.extra);
  const content = parts.join('');
  const dest = path.join(OUT_DIR, mod.file);

  if (check) {
    const existing = fs.existsSync(dest) ? fs.readFileSync(dest, 'utf8') : '';
    if (existing !== content) {
      console.error(`  ✗ ${mod.file} is out of date with index.html`);
      changed++;
    } else {
      console.log(`  ✓ ${mod.file}`);
    }
  } else {
    fs.writeFileSync(dest, content);
    const kb = (Buffer.byteLength(content) / 1024).toFixed(1);
    console.log(`  wrote src/data/${mod.file}  (${kb} KB, ${mod.decls.length} table${mod.decls.length === 1 ? '' : 's'})`);
  }
}

if (check && changed) {
  console.error(`\nextract-data: ${changed} module(s) stale — run \`node scripts/extract-data.mjs\`.`);
  process.exit(1);
}
console.log(check ? '\nextract-data: all modules current.' : '\nextract-data: done.');
